build: Exclude native stylesheets from the web-specific build script
The recent relocation of a native stylesheet from a `src` sub-directory
to a top-level `src` directory uncovered incompatibility with existing,
broad glob patterns. The `packages/block-freeform/src/style.native.scss`
was previously in a `src` sub-directory.

Native stylesheets require additional configuration to "auto-import"
various Sass variables. That configuration is unsupported by the
`bin/packages/build.js` script. Additionally, building native
stylesheets is unnecessary for web builds.

https://github.com/WordPress/gutenberg/actions/runs/16144205849/job/45558646305?pr=70644

```
Error: Undefined variable.
   ╷
18 │     color: $light-secondary;
   │            ^^^^^^^^^^^^^^^^
   ╵
  packages/block-freeform/src/style.native.scss 18:9  root stylesheet
    at Object.wrapException (/home/runner/work/gutenberg/gutenberg/node_modules/sass/sass.dart.js:1246:17)
    at /home/runner/work/gutenberg/gutenberg/node_modules/sass/sass.dart.js:71374:23
    at _wrapJsFunctionForAsync_closure.$protected (/home/runner/work/gutenberg/gutenberg/node_modules/sass/sass.dart.js:3741:15)
    at _wrapJsFunctionForAsync_closure.call$2 (/home/runner/work/gutenberg/gutenberg/node_modules/sass/sass.dart.js:28239:12)
    at Object._asyncStartSync (/home/runner/work/gutenberg/gutenberg/node_modules/sass/sass.dart.js:3705:20)
    at _EvaluateVisitor2.visitVariableExpression$body$_EvaluateVisitor0 (/home/runner/work/gutenberg/gutenberg/node_modules/sass/sass.dart.js:71380:16)
    at _EvaluateVisitor2.visitVariableExpression$1 (/home/runner/work/gutenberg/gutenberg/node_modules/sass/sass.dart.js:71354:19)
    at VariableExpression0.accept$1$1 (/home/runner/work/gutenberg/gutenberg/node_modules/sass/sass.dart.js:98828:22)
    at VariableExpression0.accept$1 (/home/runner/work/gutenberg/gutenberg/node_modules/sass/sass.dart.js:98831:19)
    at /home/runner/work/gutenberg/gutenberg/node_modules/sass/sass.dart.js:74362:42 {
  type: 'Error',
  '$error': '$error',
  formatted: 'Error: Undefined variable.\n' +
    '   ╷\n' +
    '18 │     color: $light-secondary;\n' +
    '   │            ^^^^^^^^^^^^^^^^\n' +
    '   ╵\n' +
    '  packages/block-freeform/src/style.native.scss 18:9  root stylesheet',
  line: 18,
  column: 9,
  file: '/home/runner/work/gutenberg/gutenberg/packages/block-freeform/src/style.native.scss',
  status: 1
```